const data = [
  {
    id: 1,
    imageUrl: "https://via.placeholder.com/150",
    title: "Master",
    name: "John Doe",
    age: 10,
    from: "New York, USA",
    organizationName: "Hope Foundation",
    organizationAddress: "123 Charity Lane, New York, USA",
    textFromChild: "Hi! I love exploring new things and helping others.",
    status: "Available",
    health: "Good",
    hobbies: ["Soccer", "Drawing"],
  },
  {
    id: 2,
    imageUrl: "https://via.placeholder.com/150",
    title: "Miss",
    name: "Emily Smith",
    age: 12,
    from: "London, UK",
    organizationName: "Helping Hands",
    organizationAddress: "456 Compassion Street, London, UK",
    textFromChild: "My dream is to make the world a better place.",
    status: "In Approval",
    health: "Excellent",
    hobbies: ["Reading", "Gardening", "Crafting"],
  },
  {
    id: 3,
    imageUrl: "https://via.placeholder.com/150",
    title: "Master",
    name: "Michael Brown",
    age: 9,
    from: "Sydney, Australia",
    organizationName: "Future Bright",
    organizationAddress: "789 Inspiration Ave, Sydney, Australia",
    textFromChild: "Exploring science and technology fascinates me.",
    status: "Available",
    health: "Good",
    hobbies: ["Cycling", "Puzzles"],
  },

  {
    id: 4,
    imageUrl: "https://via.placeholder.com/150",
    title: "Miss",
    name: "Sophia Johnson",
    age: 11,
    from: "Toronto, Canada",
    organizationName: "Kids First",
    organizationAddress: "321 Care Drive, Toronto, Canada",
    textFromChild: "I love spending time outdoors and learning about nature.",
    status: "In Approval",
    health: "Fair",
    hobbies: ["Dancing", "Singing"],
  },
  {
    id: 5,
    imageUrl: "https://via.placeholder.com/150",
    title: "Master",
    name: "Ethan Wilson",
    age: 13,
    from: "Cape Town, South Africa",
    organizationName: "Bright Futures",
    organizationAddress: "654 Opportunity Blvd, Cape Town, South Africa",
    textFromChild: "My favorite activity is playing chess and reading books.",
    status: "Available",
    health: "Excellent",
    hobbies: ["Chess", "Reading", "Puzzles"],
  },
  {
    id: 6,
    imageUrl: "https://via.placeholder.com/150",
    title: "Miss",
    name: "Olivia Taylor",
    age: 8,
    from: "Mumbai, India",
    organizationName: "Hope Foundation",
    organizationAddress: "123 Charity Lane, Mumbai, India",
    textFromChild: "I enjoy painting pictures of my surroundings.",
    status: "Available",
    health: "Good",
    hobbies: ["Painting", "Gardening"],
  },
  {
    id: 7,
    imageUrl: "https://via.placeholder.com/150",
    title: "Master",
    name: "Liam Anderson",
    age: 12,
    from: "Tokyo, Japan",
    organizationName: "Helping Hands",
    organizationAddress: "456 Compassion Street, Tokyo, Japan",
    textFromChild: "My dream is to travel the world.",
    status: "In Approval",
    health: "Excellent",
    hobbies: ["Traveling", "Cycling"],
  },
  {
    id: 8,
    imageUrl: "https://via.placeholder.com/150",
    title: "Miss",
    name: "Emma Thomas",
    age: 9,
    from: "Paris, France",
    organizationName: "Future Bright",
    organizationAddress: "789 Inspiration Ave, Paris, France",
    textFromChild: "I enjoy exploring art and writing stories.",
    status: "Available",
    health: "Fair",
    hobbies: ["Art", "Writing"],
  },
  {
    id: 9,
    imageUrl: "https://via.placeholder.com/150",
    title: "Master",
    name: "Noah Harris",
    age: 10,
    from: "Berlin, Germany",
    organizationName: "Kids First",
    organizationAddress: "321 Care Drive, Berlin, Germany",
    textFromChild: "My favorite thing is building LEGO structures.",
    status: "In Approval",
    health: "Good",
    hobbies: ["LEGO", "Engineering"],
  },
  {
    id: 10,
    imageUrl: "https://via.placeholder.com/150",
    title: "Miss",
    name: "Ava Martin",
    age: 13,
    from: "Moscow, Russia",
    organizationName: "Bright Futures",
    organizationAddress: "654 Opportunity Blvd, Moscow, Russia",
    textFromChild: "I love cooking and making new recipes with my friends.",
    status: "Available",
    health: "Excellent",
    hobbies: ["Cooking", "Baking"],
  },

  {
    id: 11,
    imageUrl: "https://via.placeholder.com/150",
    title: "Master",
    name: "James Wilson",
    age: 9,
    from: "New York, USA",
    organizationName: "Hope Foundation",
    organizationAddress: "123 Charity Lane, New York, USA",
    textFromChild:
      "I love playing soccer and hope to become a professional athlete.",
    status: "Available",
    health: "Good",
    hobbies: ["Soccer", "Cycling"],
  },
  {
    id: 12,
    imageUrl: "https://via.placeholder.com/150",
    title: "Miss",
    name: "Mia Brown",
    age: 11,
    from: "London, UK",
    organizationName: "Helping Hands",
    organizationAddress: "456 Compassion Street, London, UK",
    textFromChild: "I enjoy reading fantasy books and writing short stories.",
    status: "In Approval",
    health: "Excellent",
    hobbies: ["Reading", "Writing", "Gardening"],
  },
  {
    id: 13,
    imageUrl: "https://via.placeholder.com/150",
    title: "Master",
    name: "Lucas Taylor",
    age: 14,
    from: "Sydney, Australia",
    organizationName: "Future Bright",
    organizationAddress: "789 Inspiration Ave, Sydney, Australia",
    textFromChild: "I love exploring science and conducting fun experiments.",
    status: "Available",
    health: "Good",
    hobbies: ["Science Experiments", "Cycling"],
  },
  {
    id: 14,
    imageUrl: "https://via.placeholder.com/150",
    title: "Miss",
    name: "Amelia Johnson",
    age: 12,
    from: "Toronto, Canada",
    organizationName: "Kids First",
    organizationAddress: "321 Care Drive, Toronto, Canada",
    textFromChild: "Dancing and singing with my friends makes me happy.",
    status: "In Approval",
    health: "Good",
    hobbies: ["Dancing", "Singing", "Painting"],
  },
  {
    id: 15,
    imageUrl: "https://via.placeholder.com/150",
    title: "Master",
    name: "Henry Thomas",
    age: 10,
    from: "Cape Town, South Africa",
    organizationName: "Bright Futures",
    organizationAddress: "654 Opportunity Blvd, Cape Town, South Africa",
    textFromChild: "I enjoy building and fixing things around me.",
    status: "Available",
    health: "Excellent",
    hobbies: ["Engineering", "LEGO"],
  },
  {
    id: 16,
    imageUrl: "https://via.placeholder.com/150",
    title: "Miss",
    name: "Harper Anderson",
    age: 8,
    from: "Mumbai, India",
    organizationName: "Hope Foundation",
    organizationAddress: "123 Charity Lane, Mumbai, India",
    textFromChild: "I love baking and decorating cakes with my friends.",
    status: "Available",
    health: "Good",
    hobbies: ["Baking", "Cooking"],
  },
  {
    id: 17,
    imageUrl: "https://via.placeholder.com/150",
    title: "Master",
    name: "Alexander Wilson",
    age: 13,
    from: "Tokyo, Japan",
    organizationName: "Helping Hands",
    organizationAddress: "456 Compassion Street, Tokyo, Japan",
    textFromChild: "I want to travel and explore new places around the world.",
    status: "In Approval",
    health: "Excellent",
    hobbies: ["Traveling", "Photography"],
  },
  {
    id: 18,
    imageUrl: "https://via.placeholder.com/150",
    title: "Miss",
    name: "Charlotte Martin",
    age: 10,
    from: "Paris, France",
    organizationName: "Future Bright",
    organizationAddress: "789 Inspiration Ave, Paris, France",
    textFromChild: "Art and crafts are my favorite hobbies.",
    status: "Available",
    health: "Fair",
    hobbies: ["Art", "Crafting"],
  },
  {
    id: 19,
    imageUrl: "https://via.placeholder.com/150",
    title: "Master",
    name: "Benjamin Harris",
    age: 12,
    from: "Berlin, Germany",
    organizationName: "Kids First",
    organizationAddress: "321 Care Drive, Berlin, Germany",
    textFromChild: "I like solving puzzles and playing chess.",
    status: "Available",
    health: "Good",
    hobbies: ["Puzzles", "Chess"],
  },
  {
    id: 20,
    imageUrl: "https://via.placeholder.com/150",
    title: "Miss",
    name: "Isabella Taylor",
    age: 9,
    from: "Moscow, Russia",
    organizationName: "Bright Futures",
    organizationAddress: "654 Opportunity Blvd, Moscow, Russia",
    textFromChild: "I enjoy singing and performing in front of people.",
    status: "In Approval",
    health: "Excellent",
    hobbies: ["Singing", "Dancing"],
  },
];

export default data;
